### ISSUE TITLE
Google Chrome misassuming the page language

### ISSUE THREAD

**Issue by JaniL** [TKOaly/exam-archive-new#31]
<img width="332" alt="Screenshot 2021-03-29 at 14 34 07" src="https://user-images.githubusercontent.com/60955/112830971-f0402b80-909b-11eb-9cc7-f0a94642458e.png">

maybe consider adding language as html meta tag, not sure if it will help

**Comment by cxcorp** [comment]
Which page does this occur on? My Chrome just shows "Unknown" as the language, but translates Finnish text correctly to English.

**Comment by cxcorp** [comment]
Commit 9ffd988013b044098d65ea9c4adc16dca5eb3172 adds `<html lang="en">` and `lang="fi-FI"` on course names. Did this fix the issue?

**Comment by JaniL** [comment]
I think it was one of the first ten courses listed on the front page. It did fix the issue because I'm not seeing that anymore.

**Comment by cxcorp** [comment]
Great, thanks!  Do re-open the issue if it comes back.
